#!/usr/bin/env python3
"""
Interactive setup wizard for prox5.

Prompts for the bot's configuration and writes it to a .env file at the
repo root, which app.py (via python-dotenv) and `docker run --env-file .env`
both pick up automatically.

Usage:
    python setup.py
"""

import base64
import os
import sys

ENV_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env")
IN_CONTAINER = os.environ.get("RUNNING_IN_CONTAINER") == "1"

FIELDS = [
    {
        "key": "SLACK_BOT_TOKEN",
        "prompt": "Slack bot token",
        "hint": "starts with xoxb-",
        "secret": True,
        "validate": lambda v: v.startswith("xoxb-"),
    },
    {
        "key": "SLACK_APP_TOKEN",
        "prompt": "Slack app-level token",
        "hint": "starts with xapp-, needs connections:write",
        "secret": True,
        "validate": lambda v: v.startswith("xapp-"),
    },
    {
        "key": "CONFESSIONS_CHANNEL_ID",
        "prompt": "prox5 submit channel ID",
        "hint": "where approved prox5 submissions get posted, e.g. C0123456789",
        "secret": False,
        "validate": lambda v: v.startswith("C"),
    },
    {
        "key": "REVIEW_CHANNEL_ID",
        "prompt": "Review channel ID",
        "hint": "private moderator channel, e.g. C0123456789",
        "secret": False,
        "validate": lambda v: v.startswith("C"),
    },
]
ENV_KEYS = [f["key"] for f in FIELDS] + ["CONFESSIONS_KEY", "ALLOW_BROADCASTS_FROM_OP"]


def mask(value: str) -> str:
    if len(value) <= 8:
        return "*" * len(value)
    return value[:4] + "..." + value[-4:]


def prompt_field(field: dict, existing) -> str:
    label = f"{field['prompt']} ({field['hint']})"
    if existing:
        shown = mask(existing) if field["secret"] else existing
        label += f" [{shown}]"
    label += ": "

    while True:
        value = input(label).strip()
        if not value and existing:
            return existing
        if not value:
            print("  This value is required.")
            continue
        if not field["validate"](value):
            confirm = input(f"  '{value}' doesn't look right for this field, use it anyway? [y/N] ")
            if confirm.strip().lower() != "y":
                continue
        return value


def prompt_yes_no(prompt: str, default: bool) -> bool:
    suffix = "[Y/n]" if default else "[y/N]"
    while True:
        raw = input(f"{prompt} {suffix} ").strip().lower()
        if not raw:
            return default
        if raw in ("y", "yes"):
            return True
        if raw in ("n", "no"):
            return False
        print("  Please answer y or n.")


def generate_fernet_key() -> str:
    return base64.urlsafe_b64encode(os.urandom(32)).decode()


def load_existing_env(path: str) -> dict:
    values = {}
    if not os.path.exists(path):
        return values
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            values[key.strip()] = value.strip()
    return values


def main():
    print("prox5 setup wizard")
    print("-------------------")
    print(f"This will write your configuration to {ENV_PATH}\n")

    existing = load_existing_env(ENV_PATH)
    from_file = bool(existing)
    for key in ENV_KEYS:
        value = os.environ.get(key)
        if value:
            existing[key] = value

    if from_file and not prompt_yes_no("Existing .env found, reconfigure it?", default=True):
        print("Leaving .env unchanged.")
        return

    values = {}
    for field in FIELDS:
        values[field["key"]] = prompt_field(field, existing.get(field["key"]))

    print("\nCONFESSIONS_KEY encrypts stored prox5 submissions/DM channel IDs at rest.")
    if existing.get("CONFESSIONS_KEY") and prompt_yes_no("Keep the existing key?", default=True):
        values["CONFESSIONS_KEY"] = existing["CONFESSIONS_KEY"]
    elif prompt_yes_no("Generate a new key automatically?", default=True):
        values["CONFESSIONS_KEY"] = generate_fernet_key()
        print("  Generated a new CONFESSIONS_KEY. Losing this key makes existing prox5 submissions unreadable.")
    else:
        while True:
            key = input("  Paste an existing Fernet key: ").strip()
            if key:
                values["CONFESSIONS_KEY"] = key
                break

    values["ALLOW_BROADCASTS_FROM_OP"] = "1" if prompt_yes_no(
        "\nAllow the confessor to use @channel/@here/@everyone?",
        default=(existing.get("ALLOW_BROADCASTS_FROM_OP") == "1"),
    ) else "0"

    with open(ENV_PATH, "w") as f:
        f.write("# Generated by setup.py\n")
        for field in FIELDS:
            f.write(f"{field['key']}={values[field['key']]}\n")
        f.write(f"CONFESSIONS_KEY={values['CONFESSIONS_KEY']}\n")
        f.write(f"ALLOW_BROADCASTS_FROM_OP={values['ALLOW_BROADCASTS_FROM_OP']}\n")

    print(f"\nWrote {ENV_PATH}")
    if IN_CONTAINER:
        print("Starting the bot...\n")
    else:
        print("\nNext steps:")
        print("  pip install -r app/requirements.txt && python app/app.py")
        print("  # or, with Docker:")
        print("  docker build -t prox5 . && docker run --env-file .env prox5")


if __name__ == "__main__":
    try:
        main()
    except (KeyboardInterrupt, EOFError):
        print("\nAborted.")
        sys.exit(1)
